# Generated by Django 4.1.7 on 2023-04-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_tag_product_discount_price_producttag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='TagConnector',
        ),
    ]
