# Generated by Django 4.1.7 on 2023-04-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_producttag_tagconnector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
