# Generated by Django 4.1.7 on 2023-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_rename_quantity_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product.tag"
            ),
        ),
    ]
