# Generated by Django 4.1.7 on 2023-04-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='amount',
            new_name='percentage',
        ),
    ]
